version: '3.4'

services:
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: services/user.api/Dockerfile

  apigateway.api:
    image: ${DOCKER_REGISTRY-}apigatewayapi
    build:
      context: .
      dockerfile: apigateway.api/Dockerfile


  lobby.api:
    image: ${DOCKER_REGISTRY-}lobbyapi
    build:
      context: .
      dockerfile: services/lobby.api/Dockerfile

