// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shop.dal;

#nullable disable

namespace shop.dal.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20230402203824_cost")]
    partial class Cost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("shop.dal.Domain.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SushiType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0484eeb-f762-4d51-85a3-de3a2fde5014"),
                            ImagePath = "/cards/EggNigiri.png",
                            SushiType = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bd329baf-9496-4385-96c4-c28e38cf9938"),
                            ImagePath = "/cards/SalmonNigiri.png",
                            SushiType = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1de8b64f-7f49-4b8f-a5db-4f9fd2c7eaa7"),
                            ImagePath = "/cards/SquidNigiri.png",
                            SushiType = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("bbbd2b6e-a4f7-4d6a-a4eb-5d444c9b46b3"),
                            ImagePath = "/cards/MakiRoll.png",
                            SushiType = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("f63a7fc1-bf86-46aa-ba0e-8171443654bd"),
                            ImagePath = "/cards/Temaki.png",
                            SushiType = 3,
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("b9e9bb44-5d49-4335-b2c1-8a6b78a711ff"),
                            ImagePath = "/cards/Uramaki.png",
                            SushiType = 5,
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("cb037c96-ade7-40de-ae0c-3e777ad08d96"),
                            ImagePath = "/cards/Dumpling.png",
                            SushiType = 5,
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("d49a8542-74c5-4ac3-afce-53142500af57"),
                            ImagePath = "/cards/Edamame.png",
                            SushiType = 5,
                            Type = 7
                        },
                        new
                        {
                            Id = new Guid("ce09447b-1d60-47bb-996a-50404e2453ba"),
                            ImagePath = "/cards/Eel.png",
                            SushiType = 5,
                            Type = 8
                        },
                        new
                        {
                            Id = new Guid("746b9923-2e9c-456d-9774-c45b9da9c930"),
                            ImagePath = "/cards/Onigiri.png",
                            SushiType = 5,
                            Type = 9
                        },
                        new
                        {
                            Id = new Guid("8e276ae4-0111-4867-a170-ddeb4cfa8cb4"),
                            ImagePath = "/cards/MisoSoup.png",
                            SushiType = 5,
                            Type = 10
                        },
                        new
                        {
                            Id = new Guid("6affa9da-131e-486c-8bef-d66f9bf8d773"),
                            ImagePath = "/cards/Sashimi.png",
                            SushiType = 5,
                            Type = 11
                        },
                        new
                        {
                            Id = new Guid("37f4948a-8183-43df-86f8-6726b546ed2c"),
                            ImagePath = "/cards/Tempura.png",
                            SushiType = 5,
                            Type = 12
                        },
                        new
                        {
                            Id = new Guid("0dce8df4-f5cc-479a-976c-2ab8d97a465a"),
                            ImagePath = "/cards/Tofu.png",
                            SushiType = 13,
                            Type = 13
                        },
                        new
                        {
                            Id = new Guid("02e9886f-045b-416f-b7a4-ab47e5ae82a5"),
                            ImagePath = "/cards/Chopsticks.png",
                            SushiType = 13,
                            Type = 14
                        },
                        new
                        {
                            Id = new Guid("abadaac9-af83-4b2f-b3b6-14b9cabde229"),
                            ImagePath = "/cards/Menu.png",
                            SushiType = 13,
                            Type = 15
                        },
                        new
                        {
                            Id = new Guid("b3da37f3-353d-4ac9-b99e-fa0b847a21f2"),
                            ImagePath = "/cards/SoySauce.png",
                            SushiType = 13,
                            Type = 16
                        },
                        new
                        {
                            Id = new Guid("0382c0c6-8057-4fe3-bbc4-fdfa06090def"),
                            ImagePath = "/cards/Spoon.png",
                            SushiType = 13,
                            Type = 17
                        },
                        new
                        {
                            Id = new Guid("6b7e9cd0-8c37-446d-a925-e2c550d76d51"),
                            ImagePath = "/cards/SpecialOrder.png",
                            SushiType = 13,
                            Type = 18
                        },
                        new
                        {
                            Id = new Guid("b78680d2-b767-4b09-bd45-78dfec5bc4fe"),
                            ImagePath = "/cards/TakeoutBox.png",
                            SushiType = 13,
                            Type = 19
                        },
                        new
                        {
                            Id = new Guid("26b8321c-9417-4d83-b43c-76f64200e496"),
                            ImagePath = "/cards/Tea.png",
                            SushiType = 13,
                            Type = 20
                        },
                        new
                        {
                            Id = new Guid("5a3356f1-84d7-4fa6-9359-361bebf5f1e8"),
                            ImagePath = "/cards/Wasabi.png",
                            SushiType = 21,
                            Type = 21
                        },
                        new
                        {
                            Id = new Guid("fb615441-e3e0-4a0b-b0ad-2dee6d8f23e8"),
                            ImagePath = "/cards/GreenTeaIceCream.png",
                            SushiType = 21,
                            Type = 22
                        },
                        new
                        {
                            Id = new Guid("c7375ade-58d6-4e35-b577-a975df77e560"),
                            ImagePath = "/cards/Fruit.png",
                            SushiType = 21,
                            Type = 23
                        },
                        new
                        {
                            Id = new Guid("4fe311d7-6c90-4a50-ac50-e20645580e98"),
                            ImagePath = "/cards/Pudding.png",
                            SushiType = 24,
                            Type = 24
                        });
                });

            modelBuilder.Entity("shop.dal.Domain.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint");

                    b.Property<int>("DeckType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Decks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54b50c40-d4d6-464c-b030-688c1f901125"),
                            Cost = 50L,
                            DeckType = 0
                        },
                        new
                        {
                            Id = new Guid("2f4052ef-896e-460a-9c24-9824ba39c16b"),
                            Cost = 50L,
                            DeckType = 1
                        },
                        new
                        {
                            Id = new Guid("7bf5078e-6abb-4477-b8d8-3b97a4fdd060"),
                            Cost = 50L,
                            DeckType = 2
                        },
                        new
                        {
                            Id = new Guid("6183eba4-2a64-42fc-85fe-acbd61fde712"),
                            Cost = 50L,
                            DeckType = 3
                        },
                        new
                        {
                            Id = new Guid("abdfdf36-a01d-4e0c-addb-e92c17fb36b7"),
                            Cost = 50L,
                            DeckType = 4
                        },
                        new
                        {
                            Id = new Guid("485ca349-b75c-4a03-bff3-7f7a48c85327"),
                            Cost = 50L,
                            DeckType = 5
                        },
                        new
                        {
                            Id = new Guid("6a29d35d-3e8f-4800-8895-9f596d0f96d5"),
                            Cost = 50L,
                            DeckType = 6
                        },
                        new
                        {
                            Id = new Guid("cf429547-d511-4836-8385-8de7d96d8193"),
                            Cost = 50L,
                            DeckType = 7
                        });
                });

            modelBuilder.Entity("shop.dal.Domain.DeckCard", b =>
                {
                    b.Property<int>("DeckType")
                        .HasColumnType("int");

                    b.Property<int>("CardType")
                        .HasColumnType("int");

                    b.HasKey("DeckType", "CardType");

                    b.HasIndex("CardType");

                    b.ToTable("DeckCards");

                    b.HasData(
                        new
                        {
                            DeckType = 0,
                            CardType = 0
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 1
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 2
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 3
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 12
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 11
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 10
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 21
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 20
                        },
                        new
                        {
                            DeckType = 0,
                            CardType = 22
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 0
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 1
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 2
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 3
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 12
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 11
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 6
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 14
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 21
                        },
                        new
                        {
                            DeckType = 1,
                            CardType = 24
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 0
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 1
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 2
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 4
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 12
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 6
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 13
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 21
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 15
                        },
                        new
                        {
                            DeckType = 2,
                            CardType = 22
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 0
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 1
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 2
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 4
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 9
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 13
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 11
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 17
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 19
                        },
                        new
                        {
                            DeckType = 3,
                            CardType = 23
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 0
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 1
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 2
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 5
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 9
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 6
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 7
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 18
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 20
                        },
                        new
                        {
                            DeckType = 4,
                            CardType = 22
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 0
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 1
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 2
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 4
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 8
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 13
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 10
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 17
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 16
                        },
                        new
                        {
                            DeckType = 5,
                            CardType = 24
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 0
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 1
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 2
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 3
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 12
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 6
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 8
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 17
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 14
                        },
                        new
                        {
                            DeckType = 6,
                            CardType = 22
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 0
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 1
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 2
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 5
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 9
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 13
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 10
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 15
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 18
                        },
                        new
                        {
                            DeckType = 7,
                            CardType = 23
                        });
                });

            modelBuilder.Entity("shop.dal.Domain.DeckCard", b =>
                {
                    b.HasOne("shop.dal.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardType")
                        .HasPrincipalKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shop.dal.Domain.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckType")
                        .HasPrincipalKey("DeckType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("shop.dal.Domain.Deck", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
